### ISSUE TITLE
Autocomplete based on value of another parameter

### ISSUE THREAD

**Issue by potatoqualitee** [PowershellFrameworkCollective/psframework#16]
Hey Fred,
I've read that TEPP makes it possible to auto-complete based on a value (Like auto populating -User with db1's Users if `-Database db1`).

Is that possible with PSF? Claudio set a value for our auto complete but it auto completes for every `Set-DbcConfig -Name` and not just `-Name policy.datafilegrowthtype`

![image](https://user-images.githubusercontent.com/8278033/34457608-1250bd3e-edb6-11e7-93a5-112ef01f2cea.png)

**Comment by FriedrichWeinmann** [comment]
Hey Chrissy, it sure is possible to do so!
All currently bound parameters can be found in the `$fakeBoundParameter` hashtable that is available to your scriptblock.
In your example, you'd be able to check for that parameter by placing this in your completion scriptblock:
```powerShell
$fakeBoundParameter.Database
```

Available variables:
`$commandName`
The name of the command the specific parameter being provided tab completion for belongs to. It's possible to assign the same completion script to multiple parameters in multiple commands. In some cases it may be desirable to react to which command is being completed for.

`$parameterName`
The name of the parameter the tab completion is provided for. Same as for the command itself, the same tab completion can be assigned for multiple parameters. In complex completion scenarios it may be necessary to know which parameter it is.

`$wordToComplete`
What the user typed so far for the parameter you are completing. Using the simple scriptblock, it will _automatically_ filter all text by this, so you usually do not need it unless you want to optimize queries.

`$commandAst`
Complicated stuff, but basically this contains information on the entire. line. We will not go further into the details of this parameter. If you already understand ast (Abstract Syntax Trees), then it is unlikely that this guide contains any news for you.

`$fakeBoundParameters`
Similar to when you use the $PSBoundparameters variable inside a function, this parameter gives you access to the values already bound to parameters.
Note: This cannot give you access to input provided by pipeline!

**Comment by potatoqualitee** [comment]
oh wow! thank you 👍

**Comment by FriedrichWeinmann** [comment]
Glad to have been of assistance.
I'm assuming that constitutes a solved issue :)
