### ISSUE TITLE
Stop-PSFFunction throws <You cannot call a method on a null-valued expression.>

### ISSUE THREAD

**Issue by nvarscar** [PowershellFrameworkCollective/psframework#188]
In the latest version of the module (0.9.25.112), whenever EnableException is $true, the function will return:

You cannot call a method on a null-valued expression.
At line:256 char:10
+         else { $Cmdlet.ThrowTerminatingError($records[0]) }

How to reproduce:
```powershell
function test { try { throw "asd" } catch { Stop-PSFFunction -Message "test" -ErrorRecord $_ -EnableException $true} }
test
```

Issue is apparently due to $Cmdlet var being null and the following code trying to call a method from a null object:
```powershell
		if ($Cmdlet) { throw $records[0] }
		else { $Cmdlet.ThrowTerminatingError($records[0]) }
```

**Comment by FriedrichWeinmann** [comment]
Resolved in the current release
