### ISSUE TITLE
[PSCore\Linux] Path resolution fails on a Linux system when importing a module

### ISSUE THREAD

**Issue by Clebam** [PowershellFrameworkCollective/psframework#191]
Hi,

When you import a module made with PSFrameWork,

it fails loading the functions because it does not handle the path properly in the function Import-ModuleFile

We get /usr/etc/test turn into /usr\est\test

It seems Resolve-Path might help here 

 Resolve-Path /usr/etc/scripts/CentreonPowerShell\internal\scripts

Path
----
/usr/etc/scripts/CentreonPowerShell/internal/scripts

**Comment by FriedrichWeinmann** [comment]
Oh thank you very much for pointing this out!
Will have to incorporate the fix I use in PSFramework itself
(Note that the actual issue is in the PSModuleDevelopment module's templates)

**Comment by FriedrichWeinmann** [comment]
Resolved in the current release of PSModuleDevelopment template
