### ISSUE TITLE
Get Log File Path?

### ISSUE THREAD

**Issue by awickham10** [PowershellFrameworkCollective/psframework#259]
When using the filesystem logging provider is there a way to get the full path to the file being written to? If there are failures in my script I would like to send that in an e-mail as an attachment, but need the path.

**Comment by FriedrichWeinmann** [comment]
Heya,
it sure is a way to do that:
The name convention of the logfiles is:

```
<computername>_<processid>_message_<index>
```

So you can grab them by process id.

Alternatively you could consider enabling the logfile provider for task specific logfiles (though those don't include native logrotate, so I can see the attraction behind using just the default filesystem provider)
