### ISSUE TITLE
Stop-PSFFunction -EnableException

### ISSUE THREAD

**Issue by Splaxi** [PowershellFrameworkCollective/psframework#309]
A idea I want some feedback on.

Would it make sense to extend the default configuration shipped by PSFramework to include a `psframework.system.enableexception`

`Stop-PSFFunction` should be extended to look for that new configuration. Then the user only needs to make a decision for their entire machine / user profile, how they want different modules to behave when `Stop-PSFFunction` is being executed.

Then the user can either change that value based on the work they want done.

What do you think @FriedrichWeinmann ?

**Comment by FriedrichWeinmann** [comment]
I don't think that's a viable option due to it interfering with the way module designers build their modules.
Users could instead add a PSDefaultParameterValues entry in their user profile:
```powershell
$PSDefaultParameterValues['*:EnableException'] = $true
```
Which would work for all modules using the default implementation.

**Comment by Splaxi** [comment]
And that would work out of the box with the current release? 🤔

**Comment by Splaxi** [comment]
I just tested it and it works like a charm!

Thanks @FriedrichWeinmann !
