### ISSUE TITLE
Write-PSFMessageProxy should support more parameters

### ISSUE THREAD

**Issue by nyanhp** [PowershellFrameworkCollective/psframework#314]
It would be awesome if Write-PSFMessageProxy would support all parameters of Write-Host, Write-Error and Write-Information so that setting up simple aliases pointing to Write-PSFMessageProxy does not fail.

The parameters need not necessarily all be implemented, as long as they can be used through the alias.

**Comment by FriedrichWeinmann** [comment]
Implemented in 1.0.19
