### ISSUE TITLE
Configuration Schema: default

### ISSUE THREAD

**Issue by FriedrichWeinmann** [PowershellFrameworkCollective/psframework#363]
- Localization

**Comment by FriedrichWeinmann** [comment]
Released in 1.4.146

**Comment by Zhunya** [comment]
So its possible now to add translation to ./help/ru-ru and PSFramework/ru-ru?

**Comment by FriedrichWeinmann** [comment]
Hi Zhunya,
sorry about the delay, hadn't noticed this message before.
Possible: Yes.
I just don't know enough russian to do it myself.
Open to PRs :)

**Comment by Zhunya** [comment]
Thank you for reply =) Will try to make translation
