### ISSUE TITLE
Write-PSFMessage and NoNewline

### ISSUE THREAD

**Issue by raandree** [PowershellFrameworkCollective/psframework#369]
Is it possible to have a similar feature to NoNewline for Write-Host? This would be quite helpful to write the progress of a task in a sequence of dots that should be in the same line.

**Comment by FriedrichWeinmann** [comment]
Heya Raimund,
it can be added ... partially.
Basically, any individual call to Write-PSFMessage will always generate an individual message (as far as logs are concerned), but I can definitely add the option to have it not add a new line.
Would need some tweaking from a performance perspective and when it comes to the meta-information it adds to messages (the default timestamp and command name, or even the breadcrump display options, all of which can be enabled or disabled based on user preference).
Would also need a way to declare whether the next Write-PSFMessage should expect to continue a line or just act as normal (e.g. in case you draw the dots after the initial message with Write-Host and will finish the line with it as well).
So yes, needs some tweaking and some thought, but within that boundary within the realm of the possible.
Added to the implementation list of my current release "sprint".

**Comment by FriedrichWeinmann** [comment]
Released in 1.4.146
