### ISSUE TITLE
Tab Completion/PsfValidateSet Behavior

### ISSUE THREAD

**Issue by Rick-2CA** [PowershellFrameworkCollective/psframework#370]
Have outlined a scenario where tab completion fails when the Register-PSFTeppScriptblock calls another function that also uses Register-PSFTeppScriptblock.  An outline of a repeatable scenario is available at https://gist.github.com/Rick-2CA/c081772e0239a5ecaccd788a6bbb678c.

I've also run into a scenario where PsfValidateSet does not have a set (it's null) and fails all validation despite tab completion being available.  I'm still working on being able to repeat that, but mentioning it in case it ends up related.

**Comment by FriedrichWeinmann** [comment]
Found the issue, will be fixed in the new release today

**Comment by FriedrichWeinmann** [comment]
Resolved since 1.0.33
