### ISSUE TITLE
PassThru switch

### ISSUE THREAD

**Issue by PatPhelan** [PowershellFrameworkCollective/psframework#394]
I would LOVE a -PassThru switch to write the objects to the file and still pass them down the pipeline for other cmdlets to consume.

Example:

Get-ChildItem | Export-PSFCliXml -Path "C:\Temp\MyDir.byte" -PassThru | Out-Gridview -Title "Schtuff";

**Comment by FriedrichWeinmann** [comment]
Implemented and released in 1.1.59
