### ISSUE TITLE
AllowDelete attribute of a registered PSFConfig is changed to $False

### ISSUE THREAD

**Issue by exactmike** [PowershellFrameworkCollective/psframework#409]
Is this expected behavior?
```PowerShell
set-psfconfig -FullName mytest.registeredconfig -AllowDelete -value 'registeredconfig' -PassThru | register-psfconfig
get-psfconfig -FullName mytest.registeredconfig | fl FullName,AllowDelete

FullName       : mytest.registeredconfig
AllowDelete    : True

```
Then in a new PowerShell session:

```PowerShell
get-psfconfig -FullName mytest.registeredconfig | fl Fullname,AllowDelete

FullName    : mytest.registeredconfig
AllowDelete : False
```

**Comment by FriedrichWeinmann** [comment]
Hi Mike,

yes, this is actually by design.

This is based originally out of the original first design objective of the configuration system:
To be an options menu for modules.

From that point of view, all the meta-information of a setting (validation rules, serialization config, description, etc.) would be declared by the module on import.
From a perspective of updating to the next module version and changing any of that, persisting those pieces of meta-information would actually be harmful.
And _deleting_ a setting would be pretty much unthinkable (which is why back then there was also no `Remove-PSFConfig` command).

> Bottom Line: Configuration persistence always only persists the configuration values themselves.

The basic idea is to define the behavior of a setting during initialization (including whether it allows deletion).

> Docs

+ [Deleting Configuration Settings](https://psframework.org/documentation/documents/psframework/configuration/deleting-settings.html)
+ [Initialization](https://psframework.org/documentation/documents/psframework/configuration/initialize.html)

## Example in Action

To take your previous example above, in the new console, run the following line:

```powershell
Set-PSFConfig -FullName mytest.registeredconfig -AllowDelete -value 'someothervalue' -Initialize
```

Then check value and setting :)

**Comment by FriedrichWeinmann** [comment]
Oh right, before I forget that:
Defining a value during `-Initialize` is optional - that basically makes it the default value if nothing else was defined before. Not using the `-Value` parameter initializes the setting empty instead in those cases.

**Comment by exactmike** [comment]
OK, thanks very much Fred.  I understand the design intent as you explained it.  In my case I'm using the configuration system to allow a user to add and remove psfconfig settings for a module (outside of module preferences) which I want them to be able to add and remove at will.  I am therefore, probably abusing the system to some degree.  

My workaround in this case therefore is in my module code to use set-psfconfig -allowdelete just prior to remove-psfconfig.  Perhaps there is a better way to approach this.  My use case is this  [InstallManager](https://github.com/themodulecollective/InstallManager) module that I'm working on and my goal is to let a user add and remove references to packages that they want to maintain on their system using Chocolatey or PowerShellGet.

**Comment by FriedrichWeinmann** [comment]
well, that's no abuse at all!
I do that (Having users add settings beyond the module defaults) myself, both for my templating engine in PSModuleDevelopment as well as the context store in [Active Directory Management Framework](https://github.com/ActiveDirectoryManagementFramework/ADMF/blob/master/ADMF/functions/New-AdmfContextStore.ps1)

As mentioned, the supported and designed for use-cases have expanded significantly from its original inception, but some design considerations just still go back to that.

In this particular case, I'd recommend offering adding a set of commands similar to [New-AdmfContextStore](https://github.com/ActiveDirectoryManagementFramework/ADMF/blob/master/ADMF/functions/New-AdmfContextStore.ps1) and a corresponding `Remove-` function.
Which - having taken a look at your code - you obviously already do :)
And yeah, no point initializing the user settings if it's the last step before killing them.

**Comment by FriedrichWeinmann** [comment]
Btw, if you are already using the Framework:
Maybe I can coerce you to migrate all your messages to `Write-PSFMessage` ^^

```powershell
Write-Warning -Message "Not Found: InstallManager Definition for $Name"
```

Would become

```powershell
Write-PSFMessage -Level Warning -Message "Not Found: InstallManager Definition for $Name"
```

Only now you can also do

```powershell
Get-PSFMessage
Get-PSFMessage | fl *
```

Or tie it into your - or your user's - logging scheme :)

**Comment by exactmike** [comment]
Good point. This is my first project integrating PSFramework - I'll most likely do that before I move forward with publishing this work out to PSGallery.  Thanks very much for your review of this issue and the helpful conversation!

**Comment by FriedrichWeinmann** [comment]
Glad to be of help and thank _you_ for voicing your questions.
It is questions like that that help me understand how people use my module and where my documentation may need to be expanded upon - or what feature might yet be needed.

Nooow, some last advertisement before I start my long journey south ^^: If you are currently still working up on getting this released to the gallery, a few things you might find useful:

+ The [Tab Expansion](https://psframework.org/documentation/documents/psframework/tab-completion.html) is actually extremely simple to implement and allows you to add tab completion to your parameters (e.g. Name of definitions registered, ...)
+ The PSModuleDevelopment module has a templating engine that ships with default templates. `Invoke-PSMDTemplate PSFProject` will get you a module project with more tests than yours, all the automation-scripts for CI/CD and automatic release to the gallery and a folder-layout designed with PSFramework resources (such as configuration or tab completion) in mind.
