### ISSUE TITLE
Invoke-PSFProtectedCommand unable to differentiate exceptions of the same type

### ISSUE THREAD

**Issue by dgoldman-msft** [PowershellFrameworkCollective/psframework#413]
I ran in to an issue while using the Invoke-PSFProtectedCommand command. I found two like exceptions of ExceptionType: CloudException that map to  Microsoft.Rest.Azure.CloudException.

**Comment by FriedrichWeinmann** [comment]
Implemented as `-RetryCondition` parameter and part of the next release

**Comment by FriedrichWeinmann** [comment]
Released in 1.4.146
