### ISSUE TITLE
I'm not seeing the datetime being written to the logfile provider.

### ISSUE THREAD

**Issue by dtrue** [PowershellFrameworkCollective/psframework#414]
I may have inadvertently messed something up but wondering why I'm getting different data being written to the default filesystem (in app data) versus when I create a named log file.  For instance, the second column in the filesystem is a datetime that isn't being written to the specific log file version.  Thanks in advance!

**Comment by FriedrichWeinmann** [comment]
Heya, the two providers do not log the same columns in the same order!

To see what columns (and in what order) the logfile provider logs, run this line:

```powershell
Get-PSFConfigValue PSFramework.Logging.LogFile.Headers
```

You can change the header order - and which header to include - either by setting the configuration entry directly (using `Set-PSFConfig`) or by running:

```powershell
Set-PSFLoggingProvider -Name logfile -Headers Timestamp, Level, Message
```

You can pick any object on the message object as column in your output log.
To see what is available, write a message and then run:

```powershell
Get-PSFMessage | fl
```

**Comment by dtrue** [comment]
Thanks so much, and thanks for the great framework!!!
