### ISSUE TITLE
Logging with nested functions

### ISSUE THREAD

**Issue by Titus1024** [PowershellFrameworkCollective/psframework#416]
Just came across PSFramework and figuring out its logging possibilities. I'm running into an issue that I had with my previous logging solution, PSFramework seems a lot more robust so I'm hoping there's a way around it that I just haven't found yet as I'm probably just scratching the surface with it.

My issue is I have logging set up in two functions, both using Write-PSFMessage with the LogFile provider, each has their own log file. If I run the functions separately everything works beautifully, if I call one of the functions from within the other function my issue comes to light. All of the logging messages get funneled into the first function that runs. I'll put an example down below.
![image](https://user-images.githubusercontent.com/22060361/82343377-61ad4900-99b8-11ea-9d80-4de3feb333f8.png)
First 5 lines are from function 1, the remaining lines are from function 2

Is there a way to use separate streams or runspaces or something to have the log messages go to their respective log files?

**Comment by FriedrichWeinmann** [comment]
Hi Titus,
in the current iteration, that is not possible, short of cloning the entire logfile provider (I've got a template for that, if in dire need).
The next version I'm currently working on will have that significantly upgraded!
The new version will support multiple logging provider instances in parallel (any number of them).

Only problem for your scenario: You will need to also define filter rules, if you don't want the message of both functions to go to both logs (for example by filtering for module or tags attached to the message).

**Comment by FriedrichWeinmann** [comment]
Expect a few more weeks for the next release.

**Comment by Titus1024** [comment]
> Hi Titus,
> in the current iteration, that is not possible, short of cloning the entire logfile provider (I've got a template for that, if in dire need).
> The next version I'm currently working on will have that significantly upgraded!
> The new version will support multiple logging provider instances in parallel (any number of them).
> 
> Only problem for your scenario: You will need to also define filter rules, if you don't want the message of both functions to go to both logs (for example by filtering for module or tags attached to the message).

That is fantastic news, thanks for the update! I'll gladly wait for the next release.
