### ISSUE TITLE
logging Timestamp

### ISSUE THREAD

**Issue by IMBMicroscopy** [PowershellFrameworkCollective/psframework#441]
Hi, would it be possible to add milliseconds to the timestamp in the logging framework?

**Comment by FriedrichWeinmann** [comment]
Hi, sorry for the late reply.
That depends on which logging provider you use, but for the logfile provider, this is supported out of the box:
```powershell
Set-PSFLoggingProvider -Name logfile -TimeFormat 'yyyy-MM-dd HH:mm:ss.fff'
```
(plus all the [other parameters](https://psframework.org/documentation/documents/psframework/logging/loggingto/logfile.html) you would use when enabling it)

**Comment by IMBMicroscopy** [comment]
Ahhh, thanks

best
James

Dr James Springfield
Microscopy Facility Manager
Institute for Molecular Bioscience
Level 6 North | 306 Carmody Road (Building 80) | The University of Queensland | Brisbane Qld 4072 Australia
T +61 7 3346 2390 | M +61 423 021 445 | F +61 7 3346 2101 | E microscopes@imb.uq.edu.au<mailto:microscopes@imb.uq.edu.au>
Twitter @IMBmicroscopy

[cid:E1336DB2-0766-4FE0-B720-7E9B5C36318A@imb.uq.edu.au]

Connect: imb.uq.edu.au<http://imb.uq.edu.au> | Subscribe | Facebook | Twitter

This email (including any attached files) is intended solely for the addressee. It may contain private or confidential information. If you are not the intended addressee, you must take no action based on it, nor show a copy to anyone. Kindly notify the sender by reply email. Opinions and information in this email which do not relate to the official business of The University of Queensland shall be understood as neither given nor endorsed by the University. CRICOS Provider Number 00025B.

On 29 Nov 2020, at 1:56 pm, Friedrich Weinmann <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi, sorry for the late reply.
That depends on which logging provider you use, but for the logfile provider, this is supported out of the box:

Set-PSFLoggingProvider -Name logfile -TimeFormat 'yyyy-MM-dd HH:mm:ss.fff'

(plus all the other parameters<https://psframework.org/documentation/documents/psframework/logging/loggingto/logfile.html> you would use when enabling it)
