### ISSUE TITLE
logging - functionName

### ISSUE THREAD

**Issue by IMBMicroscopy** [PowershellFrameworkCollective/psframework#442]
Hi,

I get <scriptblock> or <unknown> for functionName field when logging scripts etc that are running inside separate script files which are loaded into a new sunspace. The script field shows the correct script running, but it would be great to get the actual script block name or the main script name rather than <scriptblock> or <unknown>

When I was fiddling writing my own clunky logger, I was able to get the script name using 

`Function` getScriptName {
    #If the scriptname contains Powershell.exe it must be a regular .ps1 script
    If((Split-Path ([Environment]::GetCommandLineArgs()[0]) -Leaf) -like "PowerShell*.exe") {
        $Allscripts = (Get-PSCallStack).ScriptName #get list of current running scripts in this runspace
        $scriptPath = $Allscripts[2] #get current script path
        $scriptName = Split-path $scriptPath -Leaf #get current script name        
    } 
    #Else it's an executable
    Else {
        $scriptName = ((Split-Path ([Environment]::GetCommandLineArgs()[0]) -Leaf) -replace ".exe","")
        if (!$scriptName){$scriptName = "CP"} 
    }
    return $scriptName
}`

**Comment by FriedrichWeinmann** [comment]
Hm, can't say I have plans to add this to the commands, mostly due to performance considerations (`Write-PSFMessage` needs to scale really well).
However, you can use the `-FunctionName` parameter to override the automatic detection.
