### ISSUE TITLE
[QUESTION] PSFramework is still logging but powershell cursor returned to user

### ISSUE THREAD

**Issue by liab25** [PowershellFrameworkCollective/psframework#443]
I'm seeing a really weird issue for one of my scripts. In the script I have it set to pull a bunch of data from AD and theres some logic to verify all user's emails match a specific format. At the end of the script it generates a ticket in our ticketing system. All of that works as expected but the weird this is I noticed that the ticket gets generated with the right data and my powershell cursor is free again but the log file that PSFramework is logging to is still growing in size.

Looking at the log file, it's still logging all the data where the job is iterating over all users in our AD environment. Is this the intended behavior? I would assume that the ticket creation piece could not happen until all users have been iterated through.

**Comment by FriedrichWeinmann** [comment]
Hi @liab25 ,
sorry for the late response. The logging is _asynchronous_ happening in the background.
Depending on the rate of messages you throw at it, how many logging providers you have enabled or other performance impacting factors, it may indeed have a backlog of items yet to log.
If logging were synchronous, we'd suffer performance impact on the main script.

If you close the console (e.g. when the script in a task scheduler task has run its course), it will try to flush the remaining messages for 30 more seconds before potential message loss.

You can explicitly wait for logging to complete by using `Wait-.PSFMessage`
