### ISSUE TITLE
PSProvider Splunk

### ISSUE THREAD

**Issue by itamartz** [PowershellFrameworkCollective/psframework#445]
Hi, 
Can you add support for Index in Splunk?

Currently the log cam in to the main Index.

BR,

Itamar

**Comment by FriedrichWeinmann** [comment]
Hi @itamartz ,
doesn't sound like an earth shaking update.
Added to the roadmap, will add it to the upcoming next version

**Comment by FriedrichWeinmann** [comment]
Added and released
