### ISSUE TITLE
Invoke-PSFProtectedCommand: How to retrieve internal exception

### ISSUE THREAD

**Issue by Callidus2000** [PowershellFrameworkCollective/psframework#450]
Hi,
just a question: Is it possible to use `Invoke-PSFProtectedCommand -EnableException $false` and retrieve information about the internal thrown error?
```powershell
Invoke-PSFProtectedCommand -Action "Do nothing important" -ScriptBlock {
    Write-PSFMessage -level host "Logged"
    throw "Generic-Exception"
    Write-PSFMessage -level host "NotLogged"
} -PSCmdlet $PSCmdlet -Confirm:$false -EnableException $false
if (Test-PSFFunctionInterrupt){
    Write-PSFMessage -Level Host "How2Access the exception?"
}
```

**Comment by FriedrichWeinmann** [comment]
Heya, two ways to do so:

> Option 1: The simple error variable:

```powershell
$Error[1]
```

> Option 2: Grabbing the message object

```powershell
(Get-PSFMessage -Runspace ([runspace]::DefaultRunspace.InstanceId))[-1]
```

This grabs the last message from the current runspace, which if you put it after Invoke-PSFProtectedCommand is guaranteed to be its failure warning. This object contains an ErrorRecord object which contains all the original error's data but is not actually the same data type (I did some wrapping to avoid running into serialization problems for the logging).
