### ISSUE TITLE
Using "Write-Host" as Alias results in error "cannot overwrite variable NoNewLine because the variable has been optimized"

### ISSUE THREAD

**Issue by PatrickGrub** [PowershellFrameworkCollective/psframework#453]
I have set up my logging and afterward specified the Alias:
`Set-Alias Write-Host Write-PSFMessageProxy`

Now, when I use it like `Write-Host "Test"` the below error will pop up but when using the alias `Write-Warning` it works without problems.

**What do I wrong**

![image](https://user-images.githubusercontent.com/36075173/107212309-11bf5800-6a07-11eb-8789-fdf9ba17acdb.png)

## PowerShell version

![image](https://user-images.githubusercontent.com/36075173/107212413-3a475200-6a07-11eb-8d26-86d5508722ac.png)

### Log configuration 

```PowerShell
$global:logPath = Join-Path $env:LOCALAPPDATA "test\test.txt"
$deleteLogFilesOlderThenDays = '4d' # Format example for 30 days: "30d"

$paramSetPSFLoggingProvider = @{

    # For all parameters of the "Logfile" provider read here: https://psframework.org/documentation/documents/psframework/logging/providers/logfile.html
    Name             = 'logfile'
    Enabled          = $true

    InstanceName     = 'MyTask'
    FilePath         = "$logPath\Test-%Date%.log"
    LogRotatePath    = "$logPath\Test-*.log"

    # XML, CSV, Json, Html, CMTrace
    # For CMTrace - Download Microsoft CM Viewer: https://www.microsoft.com/en-us/download/confirmation.aspx?id=50012
    FileType         = 'Json'
    JsonCompress     = $false
    JsonString       = $true
    JsonNoComma      = $false

    #Headers         = 'ComputerName', 'File', 'FunctionName', 'Level', 'Line', 'Message', 'ModuleName', 'Runspace', 'Tags', 'TargetObject', 'Timestamp', 'Type', 'Username', 'Data'
    Headers          = 'Timestamp', 'Level', 'Message', 'Data', 'FunctionName', 'Line', 'ModuleName', 'Username', 'ComputerName', 'File'
    TimeFormat       = 'yyyy-MM-dd HH:mm:ss.fff'

    LogRetentionTime = $deleteLogFilesOlderThenDays
    LogRotateRecurse = $true
}

Set-PSFLoggingProvider @paramSetPSFLoggingProvider
```

**Comment by FriedrichWeinmann** [comment]
Hi Patrick,
thanks for finding one of my more silly bugs I never noticed :(
The error message is a bit on the confusing side of things, will fix this evening.

**Comment by PatrickGrub** [comment]
@FriedrichWeinmann let me know when it's planned to fix it, but indeed a workaround would help me already. Thanks!

**Comment by FriedrichWeinmann** [comment]
Thanks for the reminder (and sorry I didn't get around to fixing this yesterday after all)
v1.5.172 is building as I type, it should resolve this issue

**Comment by PatrickGrub** [comment]
No big deal, I know it too good that during the day are coming lot of unplanned tasks! 

Awesome thanks, I will test it soon and give feedback when I have tested it.

Have a nice day!

**Comment by PatrickGrub** [comment]
Tested and it works, thanks!
