### ISSUE TITLE
Enhancement-Request: Add -Level Param to Invoke-PSFProtectedCommand

### ISSUE THREAD

**Issue by Callidus2000** [PowershellFrameworkCollective/psframework#493]
Hi,
would it be possible to add a `-Level` Param (like Write-PSFMessage) to `Invoke-PSFProtectedCommand`?
In some scripts I like to inform the user in the console about what is happening. Currently `Invoke-PSFProtectedCommand` logs this information and I have to add a `Write-PSFMessage -Level Host` to mirror the information to the console.

**Comment by FriedrichWeinmann** [comment]
Not a problem, added to the pile for the next release :)
