### ISSUE TITLE
Main process remains open when using PSFramework

### ISSUE THREAD

**Issue by PatrickGrub** [PowershellFrameworkCollective/psframework#494]
When I import the PSFramework module in my addin within Autodesk Vault and I close the main application then the process will not be terminated.
The Window is closed but still the process remains open

Code to reproduce:
+ `Import-Module -Name PSFramework` (used Version  `1.6.205` )

What I tried:
+ To remove the module again to ensure it was clean upright: `Remove-Module -Name "PSFramework" -Force -Verbose`
  + Without success

Is any similar issue known?

**Comment by FriedrichWeinmann** [comment]
Heya Patrick,
that's probably an issue with the closing event not triggering correctly, as sometimes happens in custom hosts.
This can be verified by running this as you close the runspace:

```powershell
Wait-PSFMessage
Get-PSFRunspace | Stop-PSFRunspace
[PSFramework.PSFCore.PSFCoreHost]::Uninitialize()
```

If this solves it for you, then the closing events are failing somehow.

**Comment by PatrickGrub** [comment]
This solved my issue thanks!

**Comment by andreasjordan** [comment]
I use PSFramework inside of SQL Server Agent jobs with PowerShell steps and I also need to stop the runspace as otherwise the job step does not complete and SQLPS.exe is running forever.

Just wanted to comment here so that it might save some time for other users.
