### ISSUE TITLE
Type field explanation? can we define with -Type?

### ISSUE THREAD

**Issue by xmrln4545** [PowershellFrameworkCollective/psframework#497]
In the log I see something like "Information, Debug" for Type, where does this come from? Do we have some control over that or not? This same example would again give issues when exact match parsing the log. It appears to be some kind of array instead of a string. Can we configure it's behaviour or providing -Type "..." somewhere?

**Comment by xmrln4545** [comment]
I have noticed that specifying a -Level modifies this but there is always a Debug mentioned in Type. Why is this and can this be dropped together with the comma? Maybe using Set-PSFConfig? Reason i'm asking is for exact matching parsing (ELK).

**Comment by FriedrichWeinmann** [comment]
The levels go from 1 through 9 - Verbose is 5 for example.
The lower the number, the more likely it is printed on screen for the user.

Error and Warning do not fall into that category / scale.

The column type identifies the streams the message was ultimately sent to, not the level it was generated with.
Which level goes to which stream can be configured using these settings:
```powershell
Get-PSFConfig PSFramework.Message.*.M*imum
```
> So long as you do not care about whether a message was written on screen or to the verbose stream or to the debug stream, you can safely exclude the `Type` column!
