### ISSUE TITLE
Performance issue?

### ISSUE THREAD

**Issue by xmrln4545** [PowershellFrameworkCollective/psframework#498]
Would like to know if this is to be expected? 11 seconds delay in an automation script to start logging? If so any imporvement possible? Tips, tricks?
I use:
Set-PSFLoggingProvider -Name logfile -Enabled $True -FilePath $logfile
./test_logger.ps1
Enabling c:\temp\log\PNP\XXXXXXXX-test_logger1-20210929.log
elapsed(0 minute(s) and 11 second(s))

**Comment by FriedrichWeinmann** [comment]
The logging is an infinity loop in a background runspace that sleeps a bit when idle.
It is controllod by these settings:

```
PSFramework.Logging.Interval
PSFramework.Logging.Interval.Idle
PSFramework.Logging.Interval.IdleDuration
```

By default, if you do not send a message for two minutes it will switch into idle-mode, from which it will wake up every 5 seconds and check for new messages to log. In non-idle mode it will do that every second.
This is a performance setting, trying to minimize CPU impact. The cost is still fairly low on lower cycles, so for most it should be a non-issue to disable idle mode (by equalizing the setting with non-idle).
Do not set the interval to less than 200 (ms) though, or on some systems it will ignore the sleep and eat one of your processor cores.

Also, the settings are only applied on a new cycle.
If you _persist_ the setting per configuration system, it will take effect before the first cycle of the module import.

Another factor that might affect the total time is the time needed to import PSFramework - it's grown fairly large, so the first import can take a few seconds. More so on systems with high CPU load or aggressive Antivirus.

**Comment by xmrln4545** [comment]
Excellent feedback, appreciate
