### ISSUE TITLE
Simple example of using PSFramework with Graylog

### ISSUE THREAD

**Issue by peracchi** [PowershellFrameworkCollective/psframework#504]
I can't get any message from Write-PSFMessage to my Graylog server.

If I directly use Send-PSGelfTCP or Send-PSGelfUDP I can see messages in Graylog server.

I must have missed something from documentation...

**Comment by FriedrichWeinmann** [comment]
Heya @peracchi ,
sorry about the late response.
Can you do a quick sample snippet of what you ran and how you call `Send-PSGelfTCP` directly where it works in contrast?
I'll look into it, but without a Graylog server it's not easy to triage.

**Comment by FriedrichWeinmann** [comment]
closing this due to lack of reaction. Happy to get back to this if you can help provide the requested information or provide any other lead to allow me to troubleshoot this further.
