### ISSUE TITLE
LogAnalytics Provider: Logging Properties anpassbar machen

### ISSUE THREAD

**Issue by constantinhager** [PowershellFrameworkCollective/psframework#507]
Es ist aktuell nicht möglich, wenn man mit dem LogAnalytics Provider arbeitet zu entscheiden welche Properties in den Workspace geschrieben werden. 
Diese werden immer gefüllt.

Es sollte vom Anwender entschieden werden können, welche Properties im LogAnalytics Workspace angezeigt werden sollen.

Danke.

**Comment by FriedrichWeinmann** [comment]
Implemented in 1.7.226
