### ISSUE TITLE
Terminal message control Issue

### ISSUE THREAD

**Issue by drstonephd** [PowershellFrameworkCollective/psframework#512]
Hi, 

I noticed that I get extra terminal debug messages for non-debug messages.  I will see 2 messages.  For example, I will see a critical message followed by a duplicate debug message.  I think this might be because the debug message range is 1-9.  Should it be 7-9?  I don't see the extra debug message in the "filesystem" log file. 

```
PSFramework.Message.Debug.Maximum                       9
PSFramework.Message.Debug.Minimum                       1

PSFramework.Message.Info.Maximum                        3
PSFramework.Message.Info.Minimum                        1

PSFramework.Message.Verbose.Maximum                     6
PSFramework.Message.Verbose.Minimum                     4
```

This is what I see for the following code.  

```
$DebugPreference = 'Continue'
$ErrorActionPreference = 'Continue'
$InformationPreference = 'Continue'
$VerbosePreference = 'Continue'
$WarningPreference = 'Continue'

Write-PSFMessage -Level Warning -Message "A warning message 666"
Write-PSFMessage -Level InternalComment -Message "An internal comment message 9"
Write-PSFMessage -Level Debug -Message "A debug message 8"
Write-PSFMessage -Level System -Message "A system message 7"
Write-PSFMessage -Level SomewhatVerbose -Message "A somewhat verbose message 6"
Write-PSFMessage -Level Verbose -Message "A verbose message 5"
Write-PSFMessage -Level VeryVerbose -Message "A very verbose message 4"
Write-PSFMessage -Level Significant -Message "A significant message 3"
Write-PSFMessage -Level Important -Message "A important message 2"
Write-PSFMessage -Level Output -Message "A output message 2"
Write-PSFMessage -Level Host -Message "A host message 2"
Write-PSFMessage -Level Critical -Message "A critical message 1"
```

```
WARNING: [15:38:21][<ScriptBlock>] A warning message 666
DEBUG: [15:38:21][<ScriptBlock>] A warning message 666
DEBUG: [15:38:21][<ScriptBlock>] An internal comment message 9
DEBUG: [15:38:21][<ScriptBlock>] A debug message 8
DEBUG: [15:38:21][<ScriptBlock>] A system message 7
VERBOSE: [15:38:21][<ScriptBlock>] A somewhat verbose message 6
DEBUG: [15:38:21][<ScriptBlock>] A somewhat verbose message 6
VERBOSE: [15:38:21][<ScriptBlock>] A verbose message 5
DEBUG: [15:38:21][<ScriptBlock>] A verbose message 5
VERBOSE: [15:38:21][<ScriptBlock>] A very verbose message 4
DEBUG: [15:38:21][<ScriptBlock>] A very verbose message 4
[15:38:21][<ScriptBlock>] A significant message 3
DEBUG: [15:38:21][<ScriptBlock>] A significant message 3
[15:38:21][<ScriptBlock>] A important message 2
DEBUG: [15:38:21][<ScriptBlock>] A important message 2
[15:38:21][<ScriptBlock>] A output message 2
DEBUG: [15:38:21][<ScriptBlock>] A output message 2
[15:38:21][<ScriptBlock>] A host message 2
DEBUG: [15:38:21][<ScriptBlock>] A host message 2
[15:38:21][<ScriptBlock>] A critical message 1
DEBUG: [15:38:21][<ScriptBlock>] A critical message 1
```

I also don't understand how to fully control what displays in the terminal.  InformationPreference does not seem to control levels 1-3.  Should preferences be able to turn off all message display?  

```
$DebugPreference = 'SilentlyContinue'
$ErrorActionPreference = 'SilentlyContinue'
$InformationPreference = 'SilentlyContinue'
$VerbosePreference = 'SilentlyContinue'
$WarningPreference = 'SilentlyContinue'

Write-PSFMessage -Level Warning -Message "A warning message 666"
Write-PSFMessage -Level InternalComment -Message "An internal comment message 9"
Write-PSFMessage -Level Debug -Message "A debug message 8"
Write-PSFMessage -Level System -Message "A system message 7"
Write-PSFMessage -Level SomewhatVerbose -Message "A somewhat verbose message 6"
Write-PSFMessage -Level Verbose -Message "A verbose message 5"
Write-PSFMessage -Level VeryVerbose -Message "A very verbose message 4"
Write-PSFMessage -Level Significant -Message "A significant message 3"
Write-PSFMessage -Level Important -Message "A important message 2"
Write-PSFMessage -Level Output -Message "A output message 2"
Write-PSFMessage -Level Host -Message "A host message 2"
Write-PSFMessage -Level Critical -Message "A critical message 1"
```

```
[15:29:40][<ScriptBlock>] A significant message 3
[15:29:40][<ScriptBlock>] A important message 2
[15:29:40][<ScriptBlock>] A output message 2
[15:29:40][<ScriptBlock>] A host message 2
[15:29:40][<ScriptBlock>] A critical message 1
```

[TestWritePSFMessage.zip](https://github.com/PowershellFrameworkCollective/psframework/files/8165265/TestWritePSFMessage.zip)

**Comment by FriedrichWeinmann** [comment]
Heya,

the configuration settings govern what streams the messages are written to _in addition_ to the logging, on which they have no impact. The effective streams they were written to can be found in the `Type` property on the individual messages.

The duplication in visibility of host-level messages in the default settings with `-Debug` enabled is an accepted effect, on the premise of host level messages being an exception. Also note: The behavior between setting the debugpreference and using -Debug is not quite equal.
Looking back, I probably would have done a few things differently, were I to recreate this, but since I operate under a pledge to avoid breaking changes, I prefer the risk of some irritation for a few over accidentally breaking something someone configure / setup under the current channel redirection practices.

> I also don't understand how to fully control what displays in the terminal. InformationPreference does not seem to control levels 1-3. Should preferences be able to turn off all message display?

No, they should not. Levels 1-3 correspond to `Write-Host` not `Write-Information`.
These configuration settings cover what gets written to screen without `-Verbose` or `-Debug`:

```text
PSFramework.Message.Info.Maximum
PSFramework.Message.Info.Minimum
```

Setting both to `0` will disable it.

**Comment by drstonephd** [comment]
Thanks for the explanation.  I'm a PowerShell puppy and don't want to die.  :)  I'm reading your old https://allthingspowershell.blogspot.com/2017/07/the-psframework-mastering-levels-of.html introduction to messages and see that perhaps I should not be using debug.  I used to log variable values as below.  I was thinking these are too verbose for verbose.  I would not likely want to see these except as a last resort.  Would you consider this to be a verbose message?  Or it's fine as debug, but I will see extra messages on screen if I actually am foolish enough to show debug messages on screen?

```
Write-Debug "`$oldLogonTimestamp = $oldLogonTimestamp"
```

I will keep reading.  Trying to wrap my head around relationship of Write-Host and Write-Information.  Write-Host writes to both the console and the information stream while Write-Information writes to just the information stream?  I think I will be lost a while yet.

**Comment by drstonephd** [comment]
Read about the new Write-Host is now an alias to "Write-Information -InformationAction Continue" that ignores $InformationPreference with the one exception of Ignore.  If I use the following, it does suppress level 1-3 output.

```
$InformationPreference = 'Ignore'
```

The Ignore also suppress placing an error into $error object.  This would might be bad for Write-Error, but is it for Write-Host?  I think I found a rabbit hole.

**Comment by FriedrichWeinmann** [comment]
> I think I found a rabbit hole.

A deep one. With fangs, claws and - probably - scales ^^

Curious though, thanks for delving that into it :)
