### ISSUE TITLE
Write-Debug is logged as a System message when using Write-PSFMessageProxy 

### ISSUE THREAD

**Issue by drstonephd** [PowershellFrameworkCollective/psframework#514]
I noticed that using Write-Debug logs a system message in the log file.  I would have thought this would be a "Debug" message.  Do you consider messages from the original Write-Debug to not be PSFramework "Debug" messages?  I honestly can't tell if this is a bug or a feature.  

System (7), Debug (8), InternalComment (9)

```
switch ($call.InvocationName)
{
	"Write-Host" { Write-PSFMessage -Level Important -Message $Message @splatParam }
	"Write-Verbose" { Write-PSFMessage -Level Verbose -Message $Message @splatParam }
	"Write-Warning" { Write-PSFMessage -Level Warning -Message $Message @splatParam }
	"Write-Debug" { Write-PSFMessage -Level System -Message $Message @splatParam }
	"Write-Information" { Write-PSFMessage -Level Important -Message $Message @splatParam }
	default { Write-PSFMessage -Level Verbose -Message $Message @splatParam }
}
```

**Comment by FriedrichWeinmann** [comment]
Heya Randy,

thanks for pointing this one out!
Pretty sure I meant for it to go to "Debug" instead.
On the other hand, this makes it easier to differentiate between native Debug level messages and redirected ones.

Either way, changing it would do little but reduce some potential confusion, while it might break things for others (e.g. for people who set level filters on logging providers), so I think this one is an oddity that is here to stay.
