### ISSUE TITLE
Is there a way to clear the in-memory log?

### ISSUE THREAD

**Issue by ericrlarson** [PowershellFrameworkCollective/psframework#515]
I am wanting to use Get-PSFMessage as a way to test if certain things have happened or not.  However, this requires that I be able to clear the in-memory log whenever I start my script to ensure that only entries from this execution are present.  Is there an easy way to do this?  I do not see anything like Clear-PSFMessage in the docs.

**Comment by ericrlarson** [comment]
Thank you for this.  It is very helpful!

Eric
________________________________
From: Friedrich Weinmann ***@***.***>
Sent: Tuesday, April 12, 2022 6:58 PM
To: PowershellFrameworkCollective/psframework ***@***.***>
Cc: Larson, Eric R (GE Healthcare) ***@***.***>; Author ***@***.***>
Subject: EXT: Re: [PowershellFrameworkCollective/psframework] Is there a way to clear the in-memory log? (Issue #515)

WARNING: This email originated from outside of GE. Please validate the sender's email address before clicking on links or attachments as they may not be safe.

Hi Eric,
nope, don't have a convenient tool for that yet.
Buuut ... I'll add it to the log and release a Clear-PSFMessage in the next release

In the meantime, here's a quick cheat:

function Clear-PSFMessage {
        [CmdletBinding()]
        param ()

        $field = [PSFramework.Message.LogHost].GetField('LogEntries', [System.Reflection.BindingFlags]'Static, NonPublic')
        $queue = $field.GetValue([PSFramework.Message.LogHost])
        $queue.Clear()
}

**Comment by FriedrichWeinmann** [comment]
Clear-PSFMessage is in the current release
Implemented in 2.7.235
