### ISSUE TITLE
Ever Increasing Memory Usage in PowerShell Universal

### ISSUE THREAD

**Issue by adamdriscoll** [PowershellFrameworkCollective/psframework#518]
There is something weird happening with PowerShell Universal and PSFramework. I've been trying to nail it down but could use a second set of eyes. 

I have this script running every second in my environment. 

```
[PSFramework.Message.LogHost]::MaxMessageCount = 2;

$paramSetPSFLoggingProvider = @{
    Name         = 'logfile'
    InstanceName = 'script'
    FilePath     = 'C:\temp\log.csv'
    Enabled      = $true
}
Set-PSFLoggingProvider @paramSetPSFLoggingProvider

1..10 | % {
    Write-PSFMessage -Message 'Hello' -Level 'Critical'
}
```

I then am using this for debugging. 

```

[System.Management.Automation.Runspaces.Runspace]::DefaultRunspace.InstanceId

"Filters:"

[PSFramework.Filter.FilterContainer]::Filters.GetType().GetField("_Filters", [System.Reflection.BindingFlags]::Static -bor [System.Reflection.BindingFlags]::NonPublic).GetValue($null).Values.Count

"RunspaceHost"

$field = [PSFramework.Runspace.RunspaceHost].GetField('_runspaceBoundValues', [System.Reflection.BindingFlags]'Static, NonPublic')
$field.GetValue($null).Count

"Runspace Bound Values"

$field.GetValue($null) | Select -First 1 | ForEach-Object {
    $_.Values.Count
    $_.Values | Select -First 1
}

"Script Blocks"

[PSFramework.Utility.UtilityHost]::ScriptBlocks.Count

"Log Queue:"

$field = [PSFramework.Message.LogHost].GetField('LogEntries', [System.Reflection.BindingFlags]'Static, NonPublic')
$queue = $field.GetValue([PSFramework.Message.LogHost])
$queue.Count
```

I see these runspaces in PSU. 

```
[Process:11280]: PS C:\Users\adamr\OneDrive\Documents> get-runspace | select instanceid

InstanceId
----------
286773b0-5544-4866-8fd7-72d82941c3c3
4ba204ac-2289-4af9-be77-c79cdf0374c3
bd2cb06f-0a10-4638-bbe7-5e5208e4e656
0100a85e-2044-4461-8524-74b48449e824
fd9782b4-d65c-42a7-93ff-6663daa47eac
cb0c535e-0020-4911-b789-1171e5f220e2
7fb0fec0-b584-4472-9b4a-3c72ded2d6fb
```

Running the script to output various collections out of PSF yields this. 

```
May 7, 2022 1:51 PM  Guid 
May 7, 2022 1:51 PM  ---- 
May 7, 2022 1:51 PM  06b29d3b-c387-43ac-a649-e5675f0f7680 
May 7, 2022 1:51 PM  Filters: 
May 7, 2022 1:51 PM  41 
May 7, 2022 1:51 PM  RunspaceHost 
May 7, 2022 1:51 PM  26 
May 7, 2022 1:51 PM  Runspace Bound Values 
May 7, 2022 1:51 PM  41 
May 7, 2022 1:51 PM  Key   : fcd7d79e-3276-4f04-b34e-5156659bf7ff 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 0de87a1f-1e4f-4acc-ac82-7366947adc10 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : ecfb7725-e7e3-4a8b-b861-17ad674806f4 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : d1538737-31c9-4fa7-8645-5b75f4c02b0e 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 1296c1a6-5e1a-42fa-a9e0-2b15e43d1046 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 79633b88-b5b3-4d87-93b0-a4d65bce17a4 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 64e42ae8-3ef5-46a3-96b6-0d3e1bea7219 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 75b3fac0-322f-4049-91bd-e988f67116ad 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : f30b3343-731f-4a00-a41e-ae0a87846454 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 25b00a6c-9bb4-46fa-910a-c822f6208934 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : cf789f83-325f-44d5-a637-f97c6066edec 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 6dfb8182-f7e8-4fc1-92a7-3e6d30c2763e 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : a07a056e-4be2-4918-869e-9639bd71b74d 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 82f5e870-a014-4597-a8bd-ec612829bd47 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 81366e3c-5f30-46c7-bdea-e05d4bf0e7fa 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 642c1e56-c138-40b5-b5db-6dfef0414834 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 78b4ad84-b746-426b-a515-71e5cf53c8df 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : e7d9dea2-f69b-428d-8166-628402a973bd 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : fd4452af-04be-4d1e-a792-222d726dfd86 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : c8e849b6-91f1-468b-aee1-1dd7bfefa8f0 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 2e00e732-8ed5-40cb-8713-0fee9ef96705 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : e5446703-dffd-45df-b0ae-e0a87033b6d9 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 4ac353b7-a2e8-488d-97cb-9c3a35c6a8ad 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : cb0c535e-0020-4911-b789-1171e5f220e2 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : bc0fac40-0494-4b7c-913f-cfb894c3ba56 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : f609b22c-ebb7-4791-98d6-808762e747ad 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : a991a3d7-12bc-4949-bf62-d65e669fd784 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 1b83092c-eb78-46d3-8dd0-0c4e86691e95 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : b0bb3931-c447-4417-b4b2-1658f3eb14c5 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : fe20193c-8631-4c45-b46f-8656bca3a65c 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 06b29d3b-c387-43ac-a649-e5675f0f7680 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 8062c65f-0c33-44fc-9a84-21b523a547e9 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : ee2a9980-21e6-4acc-82db-3fec7d7a2666 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : cf8b80b1-307e-4dc2-b4d6-af2382fce171 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 2f420e39-9bd2-43a1-931a-1cc97c66d71b 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 31cfff54-d258-4453-b671-6fbfbbfae7d5 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : ab98ff2a-559f-441b-a856-16bad5c0f6c0 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : cff3a299-a1ea-47af-b339-8df4d14d71b6 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 12ed3a56-1234-46c7-967f-0332fd7cb322 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : a11f949d-2910-4ea6-b656-cd42f8c97e76 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Key   : 283f47e2-367c-4938-8f2b-0d3484a52192 
May 7, 2022 1:51 PM  Value : PSFramework.Filter.FilterContainer 
May 7, 2022 1:51 PM  Script Blocks 
May 7, 2022 1:51 PM  12 
May 7, 2022 1:51 PM  Log Queue: 
May 7, 2022 1:51 PM  2 
```

The list of FilterContainer items in the RunspaceBoundValue collection continues to grow and grow until all the memory is consumed. I'm invoking scripts using:

```
var powershell = PowerShell.Create()
powershell.Runspace = runspace; 
powershell.AddScript("Test")
powershell.BeginInvoke()
```

If you have any suggestions for where I should start looking around, I'm all ears!

**Comment by FriedrichWeinmann** [comment]
Heya, thanks for noticing this bug!
Found the issue, will be fixed in the next release (baring any surprises that means tomorrow)

**Comment by adamdriscoll** [comment]
Awesome! Thanks so much for looking into this!

**Comment by Callidus2000** [comment]
A big thank you in advance for both of you, I am looking forward to the new release as my internal service suffers massively from the bug.

**Comment by FriedrichWeinmann** [comment]
Alright, v1.7.226 is in the release pipeline and should fix this problem permanently.

**Comment by Callidus2000** [comment]
Just installed to new update to my universal server, I'll report if it's a success.

**Comment by Callidus2000** [comment]
In my productive environment it seems like it is not helping. The server is been monitored by CheckMK and that's the memory graph:
![image](https://user-images.githubusercontent.com/73584079/168241062-fd080235-ded1-4800-bc7b-c884fc0e2385.png)

The last days I've scheduled a iisreset every 4h to keep the app available at last, this I've disabled after the upgrade of the module. I've completely deleted the old framework version from disk.

The environment the logic is running in is (sadly) Windows Powershell 5.1, maybe this is component of the bug behaviour?

**Comment by Callidus2000** [comment]
Throwing 1.7.227 onto the environment (Yes, I'm stalking the Repo ;-))

**Comment by FriedrichWeinmann** [comment]
Excellent - the kind of stalker I can definitely tolerate ^^
Turns out I not only had an error in enumerating the bloody RBVs, there was also a bug in detecting keys for generic RBVs.
The new iterations should not be so constrained.

Oh, and while I'm at it, considering the OP's reflection work:
The UtilityHost static class has methods to carry all that reflection load for you:

```powershell
$rbv = [PSFramework.Utility.UtilityHost]::GetPrivateStaticField([PSFramework.Runspace.RunspaceHost], "_runspaceBoundValues")
```

**Comment by Callidus2000** [comment]
I'm as excited as if it were just before Christmas.... Since the update is installed only one hour, a real interpretation is still difficult. I have drawn a rectangle in the screenshot to compare the steepness of the graph. At the moment I would say that the memory requirement is still increasing, but not as fast as before.

![image](https://user-images.githubusercontent.com/73584079/168279049-d8a5feea-42c1-4787-9411-91450894b33d.png)

**Comment by Callidus2000** [comment]
Nearly running three hours with the latest release, I fear I have to enable the scheduled iisreset again as the memory footprint is steadily growing.

![image](https://user-images.githubusercontent.com/73584079/168296666-60e147ed-bc40-4b88-aa59-44800f5cff4d.png)

**Comment by FriedrichWeinmann** [comment]
Ugh. Yeah, it's less steep than before, but it's still there :(
Will need to look into why - but I'll be honest: Without some excellent pointers such as from Adam I'm going to find the time somewhere to do the search and that means "no sooner than next week" given my current workload.

**Comment by adamdriscoll** [comment]
I will get the new version installed and run a test to again to see if I can get a memory profile.

**Comment by adamdriscoll** [comment]
I let mine run for 1 hour and it grew by about 1.5 GB. I have about 150k ScriptBlocks in memory which has the highest inclusive byte count. Strings make up the largest size but that's likely based on ScriptBlock ASTs loaded into memory. There are about 1.5 million strings in memory. 

![image](https://user-images.githubusercontent.com/1256531/168670720-8fdfac22-5b2b-4473-832e-5455290272ad.png)

Here's a random sample of some script blocks. You can see we have some duplication. I'm not sure if this is expected. 

![image](https://user-images.githubusercontent.com/1256531/168670827-a32ac187-b83c-4f39-983e-679db2c74237.png)

Is the path to the pinned reference for the first instance. 

![image](https://user-images.githubusercontent.com/1256531/168670911-61b0fb36-b7ca-47fc-939d-9c0dc51e951f.png)

I'm also seeing pinning in another static collection. 

![image](https://user-images.githubusercontent.com/1256531/168670974-8ad04685-668e-4aab-b270-52fe7a40add8.png)

I think we might be pinning Session State which could be causing the dramatic rise in memory. For example, I found that we have this session state pinned that contains all the functions for the PSFramework. 

![image](https://user-images.githubusercontent.com/1256531/168671354-c2f57969-480d-4ac1-aba0-367f2b60e6b7.png)

@FriedrichWeinmann - If there is any way I can assist with this, please let me know. I'm happy to do more memory analysis. I will also try to build it locally so I can understand the framework a bit more so I can offer more info into what I think might be going on. Based on the memory profile, this is a very similar issue to what we are seeing in dbatools.

**Comment by adamdriscoll** [comment]
I actually think I know what's happening. For some reason, the DefaultRunspace is not being set properly in PSU. It almost seems like it's opening a new runspace for every request (incorrect....). 

You can see in the next two pictures that the fourth runspace listed is new each time. The top GUID is DefaultRunspace.InstanceId. 

![image](https://user-images.githubusercontent.com/1256531/168674890-a757fb86-816e-4200-a9e1-dd758cf8d9f2.png)

![image](https://user-images.githubusercontent.com/1256531/168674952-2c5c41bf-1652-424a-88c1-00b4db29694b.png)

After poking around it looks like PSFramework cleans up runspaces bound values after 15 minutes. If PSU was busy enough, that wouldn't be frequent enough to keep memory pressure low and it would just grow. Let me see if I can figure out what's wrong with the default runspace not being set properly.

**Comment by adamdriscoll** [comment]
Sorry to keep spamming this thread but I keep learning things. I've found why the runspace changes per job and that's as expected. We actually create a new runspace per job and would explain the changes here. 

I incorrectly stated that we would eventually not keep up with cleaning out the runspace bound values but that's not the case. Every 15 minutes, it drops all of them so that probably explains the jagged memory profile in your environment, @Callidus2000. It doesn't explain why we don't get all the memory back. 

From a PSU perspective, runspace recycling will make this issue worse and running jobs in the integrated environment will as well since it uses a new runspace for each job. Even with those particular configurations, it still should be reclaiming memory. 

The hunt is still on and I know much more about PSFramework!

**Comment by adamdriscoll** [comment]
I found the issue and have submitted a PR. I'll likely put in another PR to allow changing the purge interval, but I figured I'd get this in first and figure out the configuration system next. 

I think changing the purge interval will be nice for PSU because we can create and dispose a lot of runspaces in a short amount of time.

**Comment by Callidus2000** [comment]
Just to roundup this issue documentation:
Adam's fix fixes my memory problems in my productive environment, now only a new "official" release is missing.

![image](https://user-images.githubusercontent.com/73584079/169540880-83275567-c153-4514-88c7-a53668307b6a.png)

Thanks a lot for the marvelous help of both of you.
