### ISSUE TITLE
Question: Demystifying Log Levels?

### ISSUE THREAD

**Issue by nicolas6969** [PowershellFrameworkCollective/psframework#536]
Hey all,
I'm currenlty working on a configuration where logging takes place at diferent targets based on the log level of the message. I came across the following fact, which is confusing. Maybe someone can enlighten me:

When setting the logging provider it's possible to set a value for _MaxLevel_. When setting
MaxLevel = 1 or
MaxLevel = 2

all messages with level _Warning_ are logged, but the ones with _Error_ aren't.

Checking the MessageLevel Enum gives back the following values:
Warning: 666
Error: 667

So besides the fact the values are somehow "exotic" compared to the rest (which has 1-9), why is _Warning_ logged with a **MaxLevel** of **1** or **2**, but _Error_ isn't?

**Comment by FriedrichWeinmann** [comment]
Sorry about the seriously late response - was gone on vacation for all of August and now there's this backlog ...
Anyway, good catch, will need to fix that.
Warning has been the odd one in the levels for a long time, as it is outside of the filter level range, so the level filters always were only really meant for the default levels.

Now ... what about error?
That level was introduced a lot later, mostly to support a new state for specific logging providers (Eventlog, notably), and I forgot to add it to the same level of exclusions/inclusions.
The next version - shipping today - will fix that.

Btw, to exclude warnings, use `-ExcludeWarning`. Coming with the next version of the module, there will also be an `-ExcludeError` parameter.

**Comment by FriedrichWeinmann** [comment]
Released/Resolved in 1.7.244
