### ISSUE TITLE
Many extraneous "Stopping runspace: psframework.logging" messages being logged.

### ISSUE THREAD

**Issue by DinkDev** [PowershellFrameworkCollective/psframework#537]
Hello, I've got the following PowerShell scripts that are being run by Task Scheduler in Windows Server 2016.
The task executes that AxwayToPrepareIn.ps1 script every 5 minutes.  If the script takes no action, the string 
"Stopping runspace: psframework.logging" gets logged.  I just want to supress this (or correct the issue, if possible).

Thanks for your help!

#script LoggingScriptStub.ps1:

param($scriptName)

$global:logPath = Get-Location | Join-Path -ChildPath "logs"

$deleteLogFilesOlderThenDays = "7d" # Format example for 30 days: "30d"

$paramSetPSFLoggingProvider = @{

    # For all parameters of the "Logfile" provider read here: https://psframework.org/documentation/documents/psframework/logging/providers/logfile.html
    Name             = 'logfile'
    Enabled          = $true

    InstanceName     = 'MyTask'
    FilePath         = Join-Path $logPath -ChildPath "$scriptName-%Date%.txt"
    LogRotatePath    = Join-Path $logPath -ChildPath "$scriptName-*.txt"

    # XML, CSV, Json, Html, CMTrace
    # For CMTrace - Download Microsoft CM Viewer: https://www.microsoft.com/en-us/download/confirmation.aspx?id=50012
    FileType         = 'Json'
    JsonCompress     = $false
    JsonString       = $true
    JsonNoComma      = $false

    #Headers         = 'ComputerName', 'File', 'FunctionName', 'Level', 'Line', 'Message', 'ModuleName', 'Runspace', 'Tags', 'TargetObject', 'Timestamp', 'Type', 'Username', 'Data'
    Headers          = 'Timestamp', 'Level', 'Message', 'Data', 'FunctionName', 'Line', 'Username', 'ComputerName', 'File'
    TimeFormat       = 'yyyy-MM-dd HH:mm:ss.fff'

    LogRetentionTime = $deleteLogFilesOlderThenDays
    LogRotateRecurse = $true
}

Set-PSFLoggingProvider @paramSetPSFLoggingProvider
#be sure to account for an extra 35 lines in the logging output

#Script AxwayToPrepareIn.ps1:

[CmdletBinding(
    SupportsShouldProcess
)]
param (
  $srcPath = "\\vdcs-fs1\pto-vastec3\VDCS-Mailbox\inbox",
  $destPath = "\\vdcs-f1\d$\PrepareIn",
  $delayInMinutes = 5
)

try {
  #load logging
  $scriptName = "$($MyInvocation.MyCommand.Name)".Split(".") | Select-Object -first 1
  . "$PSScriptRoot\LoggingScriptStub.ps1" -scriptName $scriptName

  $localWhatIf = [bool]$WhatIfPreference.IsPresent

  $files = [IO.Directory]::GetFiles($srcPath)

  foreach($fileName in $files) 
  { 
    $ext = [System.IO.Path]::GetExtension($fileName)
            
    if ($fileName -notlike '*.m_inproc.*' -and $ext -eq '.tar' ) 
    {
      if ( (get-item $fileName).LastWriteTime -le (get-date).AddMinutes(-1 * $delayInMinutes) ) 
      {
        Move-Item -Path $fileName -Destination $destPath -WhatIf:$localWhatIf
        Write-PSFMessage -Level Output -Message "${fileName} moved to ${destPath}"
      }
      else
      {
        Write-PSFMessage -Level Output -Message "${fileName} too young to be moved."
      }
    }   
  }
}
catch {
  Write-PSFMessage -Level Error -Message "Error in ${scriptName}: $_"
}

#output

{
    "Message":  "Stopping runspace: psframework.logging",
    "Data":  null,
    "Username":  "VDCS\\Merlin",
    "ComputerName":  "VDCS-F1",
    "FunctionName":  "Stop-PSFRunspace",
    "Level":  "Verbose",
    "Line":  9529,
    "Timestamp":  "2022-07-25 12:00:28.911",
    "File":  "C:\\Program Files\\WindowsPowerShell\\Modules\\PSFramework\\1.6.214\\PSFramework.psm1"
},
{
    "Message":  "Stopping runspace: psframework.logging",
    "Data":  null,
    "Username":  "VDCS\\Merlin",
    "ComputerName":  "VDCS-F1",
    "FunctionName":  "Stop-PSFRunspace",
    "Level":  "Verbose",
    "Line":  9529,
    "Timestamp":  "2022-07-25 12:05:27.143",
    "File":  "C:\\Program Files\\WindowsPowerShell\\Modules\\PSFramework\\1.6.214\\PSFramework.psm1"
},
{
    "Message":  "Stopping runspace: psframework.logging",
    "Data":  null,
    "Username":  "VDCS\\Merlin",
    "ComputerName":  "VDCS-F1",
    "FunctionName":  "Stop-PSFRunspace",
    "Level":  "Verbose",
    "Line":  9529,
    "Timestamp":  "2022-07-25 12:10:27.132",
    "File":  "C:\\Program Files\\WindowsPowerShell\\Modules\\PSFramework\\1.6.214\\PSFramework.psm1"
},
{
    "Message":  "\\\\vdcs-fs1\\pto-vastec3\\VDCS-Mailbox\\inbox\\test-fake.tar moved to \\\\vdcs-f1\\d$\\PrepareIn",
    "Data":  null,
    "Username":  "VDCS\\Merlin",
    "ComputerName":  "VDCS-F1",
    "FunctionName":  "AxWayToPrepareIn.ps1",
    "Level":  "Output",
    "Line":  28,
    "Timestamp":  "2022-07-25 12:15:28.184",
    "File":  "C:\\cdc\\v3\\PowerShell\\AxWayToPrepareIn.ps1"
}

**Comment by FriedrichWeinmann** [comment]
You can filter out any logging entries from a module by specifying it in the `-ExcludeModules` parameter.

Example:

```powershell
$logPath = Get-Location | Join-Path -ChildPath "logs"

$deleteLogFilesOlderThenDays = "7d" # Format example for 30 days: "30d"

$paramSetPSFLoggingProvider = @{

	# For all parameters of the "Logfile" provider read here: https://psframework.org/documentation/documents/psframework/logging/providers/logfile.html
	Name             = 'logfile'
	Enabled          = $true

	InstanceName     = 'MyTask'
	FilePath         = Join-Path $logPath -ChildPath "$scriptName-%Date%.txt"
	LogRotatePath    = Join-Path $logPath -ChildPath "$scriptName-*.txt"

	# XML, CSV, Json, Html, CMTrace
	# For CMTrace - Download Microsoft CM Viewer: https://www.microsoft.com/en-us/download/confirmation.aspx?id=50012
	FileType         = 'Json'
	JsonCompress     = $false
	JsonString       = $true
	JsonNoComma      = $false

	#Headers         = 'ComputerName', 'File', 'FunctionName', 'Level', 'Line', 'Message', 'ModuleName', 'Runspace', 'Tags', 'TargetObject', 'Timestamp', 'Type', 'Username', 'Data'
	Headers          = 'Timestamp', 'Level', 'Message', 'Data', 'FunctionName', 'Line', 'Username', 'ComputerName', 'File'
	TimeFormat       = 'yyyy-MM-dd HH:mm:ss.fff'

	LogRetentionTime = $deleteLogFilesOlderThenDays
	LogRotateRecurse = $true

	ExcludeModules = 'PSFramework'
}

Set-PSFLoggingProvider @paramSetPSFLoggingProvider
```

**Comment by DinkDev** [comment]
Thank you so much for the speedy reply.

Regards
