### ISSUE TITLE
Automatic SQL table creation/detection when using a schema other than 'dbo'

### ISSUE THREAD

**Issue by ashdar** [PowershellFrameworkCollective/psframework#550]
Hello.

If you look at the sql.provider.ps1 script, you will see that it supports schema values as a script-level configuration item. 
BUT, if you look down around line 127-132 of sql.provider.ps1 (New-DefaultSqlDatabaseAndTable), where the check for an existing table (creation of the table if it doesn't exist) is located, you will see that schema is not taken into account when testing for the existence of the table or for creating the table. 

For example, assume:
1. My SQL database has a schema called "Logging" and a table called "MyProcessing". 
1. My SQL Provider configuration is set to those that schema and table.

Obviously, the table the framework should use is "Logging.MyProcessing" - BUT the table existence code will look for "dbo.MyProcessing". If not found, the framework creates "dbo.MyProcessing". The next time logging needs to happen, the logging will find the "dbo.MyProcessing" table that got created last time and continue on it's merry way. 

The actual log entries do wind up in the correct table. IOW, Get-Query works as expected. 

I often use schemas, so I'm more likely to notice this sort of thing than most people. I might not have noticed if I had not tweaked the column data types and schema by hand. IOW, if someone relies on New-DefaultSqlDatabaseAndTable to get the table created and they use a schema other than the default/dbo, the table will get created under dbo anyway and when the framework attempts to log an entry I believe (but have not proven) that the INSERT statement will fail because it's writing to a table that doesn't exist.

**Comment by FriedrichWeinmann** [comment]
Thanks for bringing this up, yet another thing that slipped my mind on that one :(
Fix is rolling out in: https://github.com/PowershellFrameworkCollective/psframework/pull/552
