### ISSUE TITLE
Delimiter change doesn't work

### ISSUE THREAD

**Issue by LordOfRaptor-max** [PowershellFrameworkCollective/psframework#560]
If you change the CSV delimiter there will still be "," in the output CSV-file.
**Commands:**
$paramSetPSFLoggingProvider = @{
    Name         = 'logfile'
    InstanceName = 'MyTask'
    FilePath     = 'C:\Temp\Logs\TaskName-%Date%.csv'
    FileType     = 'csv'
    Headers      = 'Timestamp', 'Message', 'Tags', 'ComputerName', 'File', 'FunctionName', 'Level', 'Line', 'ModuleName', 'Runspace', 'TargetObject', 'Type', 'Username'
    Enabled      = $true
}
Set-PSFLoggingProvider @paramSetPSFLoggingProvider

$delimiter = ';'
Set-PSFConfig -FullName PSFramework.Logging.LogFile.CsvDelimiter -Value $delimiter
Get-PSFConfig -FullName PSFramework.Logging.LogFile.CsvDelimiter
Set-PSFConfig -Module PSFramework -Name 'Logging.LogFile.CsvDelimiter' -Value $delimiter
Get-PSFConfig -FullName PSFramework.Logging.LogFile.CsvDelimiter

Write-PSFMessage "Test"

**Output Commands:**
FullName                                 Value Description
--------                                 ----- -----------
PSFramework.Logging.LogFile.CsvDelimiter ;     The delimiter to use when writing to csv.
PSFramework.Logging.LogFile.CsvDelimiter ;     The delimiter to use when writing to csv.

**CSV file output:**
"Timestamp","Message","Tags","ComputerName","File","FunctionName","Level","Line","ModuleName","Runspace","TargetObject","Type","Username"
"12-7-2022 6:35:21 PM","Test","","DESKTOP",,"<ScriptBlock>","Verbose","18","<Unknown>","f1833507-60f0-40f9-ac8b-76d7c707b930",,"Verbose, Debug","DESKTOP\Raptor"

**Comment by FriedrichWeinmann** [comment]
Hi @LordOfRaptor-max,
apologies about the late response - I was somewhat drowning in work :(

The `PSFramework.Logging.LogFile.CsvDelimiter` setting applies to the default instance of logfile. To change the delimiter for your logfile, either specify it when calling `Set-PSFLoggingProvider` or set the setting for your instance (`MyTask`).

> Define during definition

```powershell
$paramSetPSFLoggingProvider = @{
    Name = 'logfile'
    InstanceName = 'MyTask'
    FilePath = 'C:\Temp\Logs\TaskName-%Date%.csv'
   FileType = 'csv'
   Headers = 'Timestamp', 'Message', 'Tags', 'ComputerName', 'File', 'FunctionName', 'Level', 'Line', 'ModuleName', 'Runspace', 'TargetObject', 'Type', 'Username'
    Enabled = $true
    CsvDelimiter = ';'
}
Set-PSFLoggingProvider @paramSetPSFLoggingProvider
```

> Update configuration for your instance

```powershell
$delimiter = ';'
Set-PSFConfig -FullName PSFramework.Logging.LogFile.MyTask.CsvDelimiter -Value $delimiter
```

With a csv delimiter, I would strongly recommend to define it together with the rest of the settings, as changing delimiters midfile is not great for CSV files.

**Comment by LordOfRaptor-max** [comment]
No problem, thanks for clarifying that.
