### ISSUE TITLE
Simple ScriptBlock in PSFTeppArgumentCompleter Broken for Strict Modes above 1.0

### ISSUE THREAD

**Issue by Alex-Larner** [PowershellFrameworkCollective/psframework#561]
The ArgumentCompleter registered with `Register-PSFTeppArgumentCompleter` will not provide any tab completion if PowerShell's strict mode is set to anything above 1.0 and the ScriptBlock is a simple script block.:

Here's the function to test it:

``` PowerShell
Set-StrictMode -Version 2.0
function Test-Tepp {
    [CmdletBinding()]
    param (
        [string]$FromTepp
    )
    Write-Host "You selected $FromTepp"
}

$SimpleScriptBlock = { 'apple', 'banana', 'caramel', 'donut' }
```

Tab completion works with this:
``` PowerShell
$FullScriptBlock = {
    param (
        $commandName,
        $parameterName,
        $wordToComplete,
        $commandAst,
        $fakeBoundParameters
    )
        'apple', 'banana', 'caramel', 'donut' |
            Where-Object { $_ -like "$wordToComplete*" } |
                ForEach-Object {
                    if ($_.Contains(' ')) { "'$_'" } else { $_ }
                }
}
Register-PSFTeppScriptblock -Name Alex.TestTepp -ScriptBlock $FullScriptBlock
Register-PSFTeppArgumentCompleter -Parameter FromTepp -Name Alex.TestTepp -Command 'Test-Tepp'
```

But tab completion does not work here:
``` PowerShell
$SimpleScriptBlock = { 'apple', 'banana', 'caramel', 'donut' }
Register-PSFTeppScriptblock -Name Alex.TestTepp -ScriptBlock $SimpleScriptBlock
Register-PSFTeppArgumentCompleter -Parameter FromTepp -Name Alex.TestTepp -Command 'Test-Tepp'
```

Using `-Mode Full` on Register-PSFTeppScriptblock for the SimpleScriptBlock doesn't work

### PSVersionTable
```
PS C:\Users\alarner> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I'm running PSFramework 1.7.249.

I also encountered the bug on the 2 other computers I tried.

We use `Set-StrictMode -Version Latest` across the board where I work, so this is sadly stopping my switch from `Register-ArgumentCompleter` to `Register-PSFTeppArgumentCompleter` in my modules.

**Comment by FriedrichWeinmann** [comment]
Thank you for the detailed and very neat report :)

Just saying, but strict mode takes away capabilities and flexibility in return for ... very little, really. :(
And what little you get out of it can be covered with PSScriptAnalyzer.

Well, I never test my code under strict mode, so yeah, things like that might happen.
I'll see what I can do to make it work with it.

**Comment by FriedrichWeinmann** [comment]
Found it and fixed it, expect an update this weekend. Will update once published.

**Comment by FriedrichWeinmann** [comment]
Hi Alex,
sorry about the delay, the latest version 1.7.270 just shipped and should include the fix
