### ISSUE TITLE
Add ListItemText support to Register-PSFTeppScriptblock

### ISSUE THREAD

**Issue by Alex-Larner** [PowershellFrameworkCollective/psframework#563]
Could you please update `Register-PSFTeppScriptblock` to support the [Completion Result's List Item Text](https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.completionresult.listitemtext?view=powershellsdk-7.3.0#system-management-automation-completionresult-listitemtext) property in addition to the current `Text` & `ToolTip` properties and add a parameter to specify what property to filter the `wordToComplete` on? i.e.

``` PowerShell
Register-PSFTeppScriptblock -Name Test.Human -ScriptBlock { 
    $Humans | Select-PSFObject 'ID as Text', 'Name as ListText', 'ToString() as ToolTip'
} -FilterOn ListText
```

## Setup Code

``` PowerShell
class Human {
    [int]$ID
    [string]$Name
    
    Human (
        [int]$ID,
        [string]$Name
    ) {
        $this.ID = $ID
        $this.Name = $Name
    }

    [string] ToString () {
        return "$($this.Name) ($($this.ID))"
    }
}

$HumanData = @(
    @{
        ID = 1
        Name = 'John Doe'
    },
    @{
        ID = 2
        Name = 'Jane Doe'
    },
    @{
        ID = 3
        Name = 'Play Dough'
    },
    @{
        ID = 4
        Name = 'Pizza Dough'
    }
)

$Humans = $HumanData | ForEach-Object { [Human]::New($_.ID, $_.Name) }

function Invoke-Human {
    [CmdletBinding()]
    param (
        [Human]$Human
    )
    Write-PSFMessage -Level Host -Message "Using $Human"
}
```

Currently the list items are shown as the text and not the tooltip, so the list view relies on knowing the IDs instead of the names, or navigating through the options one at a time to see the name in the tooltip, which negates the user-friendliness:

``` PowerShell
Register-PSFTeppScriptblock -Name Test.Human -ScriptBlock { $Humans | Select-PSFObject 'ID as Text', 'Name as Tooltip' }
Register-PSFTeppArgumentCompleter -Name Test.Human -Parameter Human -Command Invoke-Human
```
``` PowerShell
Invoke-Human -Human <Ctrl+Space>
```
![image](https://user-images.githubusercontent.com/85585421/210374273-d8ff31ea-a21f-420a-8a32-5235ae4bcfd9.png)

But if you specify the `WordToComplete` property and the `ListItemText`, you can autocomplete on the user-friendly names and show those names on the list view, while the selection renders down to the ID:

``` PowerShell
Register-PSFTeppScriptblock -Name Test.Human -ScriptBlock {
    param ($commandName, $parameterName, $wordToComplete, $commandAst, $fakeBoundParameters)
    $Humans |
        Where-Object Name -like "$wordToComplete*" |
            ForEach-Object {
                [System.Management.Automation.CompletionResult]::New($_.ID, $_.Name, 'ParameterValue', $_.ToString())
            }
}
Register-PSFTeppArgumentCompleter -Name Test.Human -Parameter Human -Command Invoke-Human
```
``` PowerShell
Invoke-Human -Human <Ctrl+Space>
```
![image](https://user-images.githubusercontent.com/85585421/210375231-e6f18612-ecff-46db-b2a3-538259d86fee.png)

``` PowerShell
Invoke-Human -Human J<Ctrl+Space>
```
![image](https://user-images.githubusercontent.com/85585421/210375287-f7bcb445-d524-419e-913f-019c91f0fcc2.png)

**Comment by FriedrichWeinmann** [comment]
Hi Alex,
implemented and released in 1.7.270
