### ISSUE TITLE
Disable-PSFLoggingProvider Exception

### ISSUE THREAD

**Issue by Sekers** [PowershellFrameworkCollective/psframework#578]
**Issue >** I am trying the new Disable-PSFLoggingProvider function and am receiving an error. However, it does seem to still unlock the logfile.

**Command >** `Disable-PSFLoggingProvider -Name $paramSetPSFLoggingProvider.Name -InstanceName $paramSetPSFLoggingProvider.InstanceName`

**Error >** Disable-PSFLoggingProvider: Exception calling "Drain" with "1" argument(s): "Logging was concluded, but timeout was reached while waiting for the final sequence of the logging provider to complete."

**More Details >** 
PSFramework version: 1.7.270 
Same issue with x64 Desktop & Core (have not tried 32-bit PS)
Log provider used: logfile (to CSV)

**Comment by FriedrichWeinmann** [comment]
Hi @Sekers ,
thanks for reporting this and sorry for the late response.
I found the bug on this one and resolved it (a bad timestamp comparison). That said, it was in the final wait process after everything else was already concluded, so yes, the file getting released beforehand was expected.

In other words, the error was cosmetic for your purposes and will be gone in the next release (soon(tm)).

**Comment by FriedrichWeinmann** [comment]
Implemented in 1.8.289
