### ISSUE TITLE
Error when using Write-PSFMessage with '-NoNewLine' parameter

### ISSUE THREAD

**Issue by heizkoerperchen** [PowershellFrameworkCollective/psframework#586]
In the latest release there was a change introduced to add a parameter 'NoNewLage' in 'library/PSFramework/Commands/WritePSFMessageCommand.cs' line 929:

            if (NoNewLine)
                    ps.AddParameter("NoNewLage", NoNewLine.ToBool());

This is causing the following error when using the '-NoNewLine' parameter:

Write-PSFMessage : A parameter cannot be found that matches parameter name 'NoNewLage'.

**Comment by FriedrichWeinmann** [comment]
Thanks for reporting this!
Will be fixed in the next version ( soon(tm) )

**Comment by FriedrichWeinmann** [comment]
Again, thanks for finding this (and apologies for the inconvenience).
Fixed and released in 1.8.291

**Comment by heizkoerperchen** [comment]
Thanks for fixing this!
