### ISSUE TITLE
Info Request: Determine the currently used logfile name

### ISSUE THREAD

**Issue by Callidus2000** [PowershellFrameworkCollective/psframework#609]
Hi Fred,
is it possible to find the fullname of the currently active default logfile? Found nothing in the PSFConfig values or the logging providers.

-Sascha aka callidus2000

**Comment by FriedrichWeinmann** [comment]
Hi Sascha,
sorry, but the only thing you get is the path to the folder:

```powershell
Get-PSFConfigValue -FullName PSFramework.Logging.FileSystem.LogPath
```

The actual filename is auto-managed

**Comment by Callidus2000** [comment]
Thanks for the confirmation
