### ISSUE TITLE
MethodInvocationException: Exception calling "ConvertFromPersistedValue" with "2" argument(s): "Index was outside the bounds of the array."

### ISSUE THREAD

**Issue by azra1l** [PowershellFrameworkCollective/psframework#650]
I'm getting the above error message whenever i import the psframework module.
It only happens the first time i import the module for a given session.

I couldn't find any issues with my other scripts for which i use psframework, so no idea what is causing this error.

How can i find the problem without resetting my whole config?

**Comment by azra1l** [comment]
Unfortunately i store the config in files, and the values are arrays of psobjects, which are stored encoded. Is there a way to decode them easily?

**Comment by azra1l** [comment]
That doesn't return any broken settings. 
I made a few persistent changes to PSFramework.Logging.FileSystem, this is what comes up in $properties per your script:
PSFramework.Logging.FileSystem.LogPath       : String:D:\Logs\PowerShell
PSFramework.Logging.FileSystem.ModernLog     : Bool:true
PSFramework.Logging.FileSystem.MaxLogFileAge : Timespan:24192000000000

I also have several configs stored in files, for other modules. I will modify your script to parse them as well.

**Comment by azra1l** [comment]
HKLM:\SOFTWARE\Microsoft\WindowsPowerShell\PSFramework\Config\Default contains no config, and the Enforced variant's don't exist yet.

The config files for other modules shouldn't even be touched when psframework is imported, as i import them manually in my scripts.

Oddly enough, i found this: C:\ProgramData\PowerShell\PSFramework\Config\psf_config.json, no idea how it ended up here, maybe from when i first messed with psframework, but the error just showed up recently. It appears to hold all the default values.

I modified your script to parse it's contents:

```
$properties = Get-Content C:\ProgramData\PowerShell\PSFramework\Config\psf_config.json | ConvertFrom-Json
$broken = foreach ($property in $properties) {
    try { $null = [PSFramework.Configuration.ConfigurationHost]::ConvertFromPersistedValue($property.value, $property.type) }
    catch {
        [PSCustomObject]@{
            FullName = $property.Name
            Type     = $type
            Value    = $value
            Data     = $property.Value
        }
    }
}
$broken | Format-List
```

and it returned a single 

```
FullName :
Type     :
Value    :
Data     :
```

I moved the file, and now the error is gone, and everything appears to work as expected. Thanks!

**Comment by azra1l** [comment]
Sorry if you wanted to keep this open :S

**Comment by azra1l** [comment]
Here is the file, if this helps:

[psf_config.zip](https://github.com/user-attachments/files/18166977/psf_config.zip)

I found it odd that it has several path settings which point to my userprofile, even though the file was in the system config path...

**Comment by FriedrichWeinmann** [comment]
Already, finally got the time to look at it. Thank you very much for the config file.
Looks like at some point you accidentally registered _everything_ to the FileSystem scope.

But I found the offending entry:
> PSFramework.Logging.EventLog.TagToID
The key issue: PSFramework has a bug, where persisting empty hashtables fails to import them.
Thank you very much for reporting this issue, will be fixed in the next release (but you probably want to remove the file anyway)

**Comment by azra1l** [comment]
As always, thanks a ton and merry christmas <3
